Tammy review
tammytamayao/reactonrails-blog-app pull request #3
Opened 2023-03-07 01:25 UTC by tammytamayao

2023-03-07 02:14 UTC, rafael-parayno requested changes

2023-03-07 02:14 UTC, rafael-parayno commented on webpack.config.js
> +};
add new line

2023-03-07 02:14 UTC, rafael-parayno commented on src/sessions/SignUp.tsx
> +export default SignUp
add new line

2023-03-07 02:14 UTC, rafael-parayno commented on src/sessions/LogIn.tsx
> +export default LogIn
add new line

2023-03-07 02:14 UTC, rafael-parayno commented on src/components/Post.tsx
> +export default Post;
add new line

2023-03-07 02:14 UTC, rafael-parayno commented on src/components/NewPost.tsx
> +export default NewPost;
add new line

2023-03-07 02:14 UTC, rafael-parayno commented on src/components/EditPost.tsx
> +export default EditPost;
add new line

2023-03-07 02:14 UTC, rafael-parayno commented on src/components/EditPost.tsx
> +        console.log(post)
do we need this console.log. remove this

2023-03-07 02:14 UTC, rafael-parayno commented on src/components/NewPost.tsx
> +    fetch(url, {
can you use axios for this. so then add axios interceptor. so we dont need to always add the base url.

2023-03-07 07:01 UTC, tammytamayao commented on src/components/EditPost.tsx
> +        console.log(post)
done

2023-03-07 07:14 UTC, tammytamayao commented on src/sessions/LogIn.tsx
> +export default LogIn
done

2023-03-07 07:14 UTC, tammytamayao commented on src/sessions/SignUp.tsx
> +export default SignUp
done

2023-03-07 07:22 UTC, tammytamayao commented on src/components/Post.tsx
> +export default Post;
done

2023-03-07 07:22 UTC, tammytamayao commented on src/components/EditPost.tsx
> +export default EditPost;
done

2023-03-07 07:23 UTC, tammytamayao commented on webpack.config.js
> +};
done

2023-03-07 07:23 UTC, tammytamayao commented on src/components/NewPost.tsx
> +export default NewPost;
done

2023-03-08 01:07 UTC, tammytamayao commented on src/components/NewPost.tsx
> +    fetch(url, {
done. Changes pushed to new branch named AxiosConfig

2023-03-08 12:16 UTC, rafael-parayno approved these changes

2023-03-09 01:08 UTC, merged