Comments front end
tammytamayao/reactonrails-blog-app pull request #8
Opened 2023-03-09 09:53 UTC by tammytamayao

- CRUD front-end comments feature of the app
- connected the front-end to the back-end rails API

2023-03-10 05:40 UTC, rafael-parayno requested changes

2023-03-10 05:40 UTC, rafael-parayno commented on src/comments/EditComment.tsx
> +export default EditComment;
add new line

2023-03-10 05:40 UTC, rafael-parayno commented on src/comments/NewComment.tsx
> +export default NewComment;
add newline

2023-03-10 05:40 UTC, rafael-parayno commented on src/config/AxiosConfig.tsx
> +export { baseURL, client }
add newline

2023-03-10 06:07 UTC, tammytamayao commented on src/config/AxiosConfig.tsx
> +export { baseURL, client }
done

2023-03-10 06:07 UTC, tammytamayao commented on src/comments/NewComment.tsx
> +export default NewComment;
done

2023-03-10 06:07 UTC, tammytamayao commented on src/comments/EditComment.tsx
> +export default EditComment;
done

2023-03-13 06:29 UTC, rafael-parayno approved these changes

2023-03-13 06:55 UTC, merged